version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

  jobs:
    pre_build:
      - "jupyter-book config sphinx doc/"

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  builder: html
  fail_on_warning: true
